-- Code generated by protoc-gen-twirp_eclier v0.0.1DO NOT EDIT
-- source: test.proto

script.verb = "hello_world:speak"
script.help = "Executes method speak on service hello_world for twirp package us.xeserv.api.hello_world"
script.author = "machine-generated"
script.version = "v0.0.1"
script.usage = ""

local flag = require "flag"
local svc = require "svc"

local fs = flag.new()

-- flags for Words
fs:string("message", "", "value for message arg message")

script.usage = fs:usage()

function run(arg)
  if arg[1] == "-help" or arg[1] == "--help" then
    print(fs:usage())
    return
  end

  arg[0] = script.verb
  local flags = fs:parse(arg)

  local resp = svc.new(apiURL, token):hello_world():speak(flags)

  print("message:\t\t" .. tostring(resp.message))
end
