// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Words struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Words) Reset()         { *m = Words{} }
func (m *Words) String() string { return proto.CompactTextString(m) }
func (*Words) ProtoMessage()    {}
func (*Words) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_fa7b6876f4f07dc3, []int{0}
}
func (m *Words) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Words.Unmarshal(m, b)
}
func (m *Words) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Words.Marshal(b, m, deterministic)
}
func (dst *Words) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Words.Merge(dst, src)
}
func (m *Words) XXX_Size() int {
	return xxx_messageInfo_Words.Size(m)
}
func (m *Words) XXX_DiscardUnknown() {
	xxx_messageInfo_Words.DiscardUnknown(m)
}

var xxx_messageInfo_Words proto.InternalMessageInfo

func (m *Words) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Words)(nil), "us.xeserv.api.Words")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_fa7b6876f4f07dc3) }

var fileDescriptor_test_fa7b6876f4f07dc3 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x2d, 0xd6, 0xab, 0x48, 0x2d, 0x4e, 0x2d,
	0x2a, 0xd3, 0x4b, 0x2c, 0xc8, 0x54, 0x52, 0xe4, 0x62, 0x0d, 0xcf, 0x2f, 0x4a, 0x29, 0x16, 0x92,
	0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x8d, 0x9c, 0xb9, 0xb8, 0x3c, 0x52, 0x73, 0x72, 0xf2, 0xc3, 0xf3, 0x8b, 0x72, 0x52,
	0x84, 0x4c, 0xb9, 0x58, 0x83, 0x0b, 0x52, 0x13, 0xb3, 0x85, 0x44, 0xf4, 0x50, 0x4c, 0xd2, 0x03,
	0x1b, 0x23, 0x85, 0x55, 0x54, 0x89, 0xc1, 0x89, 0x3d, 0x8a, 0x15, 0x6c, 0x7f, 0x12, 0x1b, 0x98,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x43, 0x4a, 0xb9, 0x4e, 0x94, 0x00, 0x00, 0x00,
}
